### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by pauloust** [illidanlab/T-LSTM#10]
Hi, 
I read your article, it is very good ! I try to apply your code on another dataset but I can't understand the format of the data in clustering_data_1D.mat. When using the `generate_batches` function you obtain `x`, `t`and `a`which are respectively 3D, 2D and 1D arrays but i can't understand what are the information they carry. Could you detail these three elements for me to construct the same structure from my dataset and then apply your model ? 

Thank you very much.

Paul L

**Comment by baytasin** [comment]
Hi Paul, 
I'm so sorry for my late reply and thank you very much for your interest in our paper. The data tensor, x, has the size of [mini batch size x sequence length x dimensionality]. x contains the time series data. Dimensionality > 1 if it's multivariate. Time tensor contains the elapsed time between each time step and its size is [mini batch size x sequence length]. t[:,0] is always 0. Actually, you may ignore a. x and t are required and if you are dealing with a supervised problem, a tensor for the label is required. 

I'm closing this issue for now. Please let me know if you have further questions.
Inci
