### ISSUE TITLE
Input Data Format 

### ISSUE THREAD

**Issue by shradhit** [illidanlab/T-LSTM#11]
Hi illidanlab, 
 
Congrats on the great paper and thank you for sharing T-LSTM code! 

I tried to run the code using the synthetic data provided; ‘Clustering_Data_1D.mat.tar.gz’ and the code works perfectly, but I am struggling to understand the input data format required for T-LSTM AE. My aim is to run the code on different EHR data (rather than EMRBot or PPMI) to obtain patient representation using your method.

•	In issue #10, the data format is described as (mini batch size x sequence length x dimensionality).
              o  What is the intuition behind choosing the number of mini-batches? Do you group patients with similar temporal pattern (e.g. # of visits) and number of dimensionality (e.g. lab values)?    
              o  The dimensionality, in the paper and the synthetic data, is 5. I assumed this refers to the number of lab values available for a patient? If so, what if a patient doesn’t have exactly 5 lab values? Is padding the missing data for this patient with zero makes sense? 
•	I am also interested to include diagnostic codes and medications to the input data. My understanding is the current synthetic data only has lab values
              o  Do you have any intuition about how I can also incorporate the diagnostic codes or medication codes?

Thank you for your time in advance.

**Comment by baytasin** [comment]
Hi Shradhit,

Thank you very much for your interest in our work. I tried to answer your questions below.
- What is the intuition behind choosing the number of mini-batches? Do you group patients with similar temporal pattern (e.g. # of visits) and number of dimensionality (e.g. lab values)?
Mini-batches can be formed with random sampling. To train t-lstm, we need a dataset of patients with the same dimensionality. They may have a different number of time steps (visits) but, the number of attributes at each time step should be the same. In this implementation, after I randomly split patients into train and test, I had formed mini-batches of patients with the same number of visits to avoid zero padding. However, you may use zero padding and form the mini-batches completely random as well.
- The dimensionality, in the paper and the synthetic data, is 5. I assumed this refers to the number of lab values available for a patient? If so, what if a patient doesn’t have exactly 5 lab values? Is padding the missing data for this patient with zero makes sense?
Here are some suggestions. If your patients have missing values at a visit, we may first check the missing value rate. We should be careful about imputing healthcare data. If almost all the values are missing, we may discard that visit (which would introduce irregularity). If the number of missing attributes is not very high, you may impute them using the values in the previous visit of the same patient. Imputing lab values with zero may be misleading. We should either use the same patient's previous information or look at the statistics of other patients in the dataset who belong to the same category. 
- I am also interested to include diagnostic codes and medications to the input data. My understanding is the current synthetic data only has lab values. Do you have any intuition about how I can also incorporate the diagnostic codes or medication codes?
We do not have to use lab results. You are free to include diagnostic or medication codes. You do not need to change the code. You just need to represent that information as vectors. We consider them multivariate time series. At each time step (visit), we need a vector. If you have lab results, you can put them in a vector. If you have medical codes, you can simply represent them as one-hot, multi-hot vectors using a dictionary, or you may consider learning embeddings (dense vectors) for medical codes, e.g., https://github.com/mp2893/med2vec

Best,
Inci
