### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by luomancs** [illidanlab/T-LSTM#6]
Hi, I am interested in your work of Patient Subtyping via Time-Aware LSTM Networks, the experiment done with Parkinson data, I am trying to reproduce the result you mentioned in the paper. It is nice that I could run your code successfully, but I am not sure about the data that you mentioned containing 319 features and the 82 symptoms. could you tell me how can I get this data? thanks for your help.

**Comment by baytasin** [comment]
Thank you very much for your interest in our work. We used the preprocessed data prepared by Xi Zhang and their team for PPMI challenge. You could contact them for data details. I do not have the data anymore. Please feel free to contact me if you have any other questions.
